language: node_js
node_js:
- '8'
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run webpackprod
- gulp praise
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/ww18/koa2support.git
after_script:
- tar czvf www.tar ./config ./controller ./model ./dist ./views ./app.js
- scp www.tar wenwen:/www
- ssh wenwen
- tar zxvf www.tar
- exit
before_install:
- openssl aes-256-cbc -K $encrypted_d7a4938d016d_key -iv $encrypted_d7a4938d016d_iv
  -in baidu_rsa.enc -out baidu_rsa -d
- chmod 600 baidu_rsa
- cp baidu_rsa ~/.ssh/baidu_rsa
- cp baidu_config ~/.ssh/config
