language: node_js
node_js:
- '8'
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run webpackprod
- gulp praise

branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/ww18/koa2support.git

