language: node_js
node_js:
- '8'
install: npm install
cache:
  directories:
  - node_modules
script:
- npm run webpackprod
- gulp praise
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/ww18/koa2support.git
after_success:
- sshpass -p ${DEPLOY_PASS} scp -o stricthostkeychecking=no -r ./* ${DEPLOY_USER}@180.76.99.112:/root/www/

