language: node_js
node_js:
  - "8"
install: npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run webpackprod
  - gulp praise

after_script:
  - git init
  - git config user.name "ww"
  - git config user.email "476848607@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: https://github.com/ww18/koa2support.git